### ISSUE TITLE
[Feature Request] Let XSSAnalyzer allow (only) style-src unsafe-inline

### ISSUE THREAD

**Issue by denydias** [enlightn/enlightn#108]
**Is your feature request related to a problem? Please describe.**
Kinda. [Enlightn\Enlightn\Analyzers\Security\XSSAnalyzer documentation](https://www.laravel-enlightn.com/docs/security/xss-analyzer.html) mentions `default-src` and `script-src` specifically. As such, one may understand (like I did) that `unsafe-inline` could be accept in `style-src`, but it doesn't. The analyzer code forbids any `unsafe` word anywhere in the header value.

**Describe the solution you'd like**
It's expected that `content-security-policy` should not allow `unsafe-inline` for `default-src` and `script-src`. This surely mitigates attack vectors in unsafe code (from the application itself or its dependencies). But inline CSS attacks is quite unusual and much harder to accomplish than in js code. It would be quite nice to allow that particular use case.

**Describe alternatives you've considered**
One alternative would be allowing the analyzer be configured to allow specifically `/style-src:.*unsafe-inline.*;/` regex.

**Additional context**
On applications using pre-built admin panels, it's quite common for dependencies to use `style` attributes in elements. For instance, a pretty regular application using [jeroennoten/laravel-adminlte](/jeroennoten/laravel-adminlte) and some of @jeremykenedy packages (user, roles, logger and such) can easily have +40 files with many entries showing inline styles. Although this could be done by a developer, it's quite time consuming and creates a maintenance burden as the changes should now be tracked for upstream changes.

**Comment by paras-malhotra** [comment]
Unsafe inline is not recommended even in style src. A very common attack vector is replacing the login button on the site with a vulnerable website link instead. Mike West did a talk called [Scriptless Attacks: Stealing the Pie Without Touching the Sill](https://mikewest.org/2013/09/xss-no-the-other-s-cssconfeu-2013/) on this (attack vectors that use style injection instead of script injection) in 2013.

If you are using `unsafe-inline`, you may choose to turn off this analyzer instead.

**Comment by denydias** [comment]
Thanks for replying. Yeah, know that you mention that attack surface, I regret asking this as a feature request. Just leave it as is for good.
