### ISSUE TITLE
[Bug Report] Enlightn brings GPL code with it, rendering the licence check useless

### ISSUE THREAD

**Issue by ZeWaren** [enlightn/enlightn#172]
### Versions

* PHP version: N/A
* Laravel version: N/A
* Enlightn version: 2.7.0
* Enlightn Pro version (if applicable): N/A

### Description

Enlightn has GPL code in its dependencies.

The [License Analyser](https://www.laravel-enlightn.com/docs/security/license-analyzer.html) check reports it.

This check is supposed to ensure developers don't depend on copyleft code by mistake, and enlightn sabotages it by bringing such code in the project.

### Steps to Reproduce

Install enlightn on a brand new project:

```
# composer create-project laravel/laravel example-app
# composer require enlightn/enlightn
# composer show | grep enlightn
enlightn/enlightn                  v2.7.0   Enlightn - Your performance & security consultant, an artisan command away.
enlightn/security-checker          v1.11.0  A PHP dependency vulnerabilities scanner based on the Security Advisories Database.
# php artisan vendor:publish --tag=enlightn
```

Run the licence check:

    # php artisan enlightn 'Enlightn\Enlightn\Analyzers\Security\LicenseAnalyzer'

**Expected behavior:**

     Check 1/1: Your application does not rely on dependencies you are not legally allowed to use. Passed

**Actual behavior:**

```
Check 1/1: Your application does not rely on dependencies you are not legally allowed to use. Failed
Your application has a total of 1 package(s) that you may not be legally allowed to use. By default, we assume the MIT, Apache-2.0, ISC, BSD Clause 2 & 3 and LGPL licenses to be legally valid for use for proprietary or commercial applications. However, you are fre
e to change this in the Enlightn config. Unsafe packages include [phpmyadmin/sql-parser: GPL-2.0-or-later]
```

### Additional Information

Here's the part of the dependency tree leading to the triggering package:
```
enlightn/enlightn v2.7.0 Enlightn - Your performance & security consultant, an artisan command away.
|--larastan/larastan ^2.0
|  |--phpmyadmin/sql-parser ^5.8.2
```

**Comment by paras-malhotra** [comment]
This is not due to a direct dependency of Enlightn. In fact, we make sure that we don't use any code that imposes GPL or other restrictive licenses. This is a dependency of Larastan and in fact Larastan 2.1 introduces this.

There are two ways you can avoid this dependency:
1. Use a version of Larastan prior to 2.1
2. Set the [Larastan config](https://github.com/larastan/larastan/blob/2.x/docs/custom-config-parameters.md) to disable the schema scan. This way you will not be using any code that pulls in a restrictive license

**Comment by ignaciogc** [comment]
@ZeWaren is correct. 

Enlightn directly brings in the dependency for larastan, which through its dependencies triggers the failure of the License Analyser.

I did not have the **phpmyadmin/sql-parser** package on my application, but it was added after adding enlightn through the **larastan/larastan** package. One of the recommendations is to only install as --dev, but that's not recommended by enlightn so that we can run the checks in production (if needed).

It seems like phpmyadmin/sql-parser is looking at changing their license to LGPL, but until that happens enlightn is introducing problems itself - https://github.com/phpmyadmin/sql-parser/issues/448

@paras-malhotra , the composer.json file for enlightn lists `larastan/larastan": "^2.0"` as a requirement, which will of course install 2.1 if available.

The requirement should be updated `~2.0.0` or `2.0.*` to make sure 2.1 is not installed, and the GPL dependency is avoided, until phpmyadmin/sql-parser completes the license change.
