### ISSUE TITLE
json_decode as objects fed to foreach loop [Bug Report]

### ISSUE THREAD

**Issue by jasperf** [enlightn/enlightn#33]
### Versions

* PHP version:7.4
* Laravel version:8.24.0
* Enlightn version: v1.9.0
* Enlightn Pro version (if applicable):

### Description

Been starting to use your tool and love it. Free version for now but if all goes well we will upgrade to Pro for additional tests of our Laravel Vue application

`json_decode` without associative array set as true followed by `foreach` is said to be non iterative though objects can be iterated through as well. See php.net documentation on `foreach` loops and `json_decode`

### Steps to Reproduce

example code Enlightn goes through:
```php
$pageList = json_decode($item->json);

foreach ($pageList as $page) {
    if (isset($page->deadlink) && $page->deadlink != 1) {
        $original = Page::find($page->id);
        if ($original) {
            $page->slug = $original->slug;
            $page->homepage = $original->homepage;
        }
    }
}
```
and where it considers fed data cannot be used by the `foreach` loop.
**Expected behavior:**

No positive issue shown as objects loaded should work fine in `foreach` loop

**Actual behavior:**

Error occurs that a non iterable item has been found

### Additional Information

Wrote more about it at [Laracasts Discussion](https://laracasts.com/discuss/channels/laravel/entlighn-non-interable-foreach-loop).

**Comment by paras-malhotra** [comment]
Hi @jasperf, glad you like it!

Can you please upgrade to v1.10.0 and run the `enlightn` Artisan command with the `--details` flag? Docs [here](https://www.laravel-enlightn.com/docs/getting-started/usage.html#view-detailed-error-messages). We introduced this yesterday to enable better understanding of error messages.

**Comment by jasperf** [comment]
When I run all with latest and the `--details` flag I get

```
...
At /app/Http/Controllers/Dashboard/PublishController.php, line 276: Argument of an invalid type mixed supplied for foreach, only iterables are supported.
...
```

For the same code:

```
...
$insertData = $this->project->menus->map(function ($item, $key) {
// Clear on published database
PublishedMenu::destroy($item->id);

$pageList = json_decode($item->json);

foreach ($pageList as $page) {
    if (isset($page->deadlink) && $page->deadlink != 1) {
        $original = Page::find($page->id);
        if ($original) {
            $page->slug = $original->slug;
            $page->homepage = $original->homepage;
        }
    }
}
..
```

So I am getting more details @paras-malhotra . Still not quite sure what to make of it yet.

**Comment by paras-malhotra** [comment]
@jasperf Enlightn uses PHPStan under the hood for this check. 

PHPStan looks in the docs, function/method signatures, etc. to determine what type any variable is. It's not possible for PHPStan to determine what type `$item` is, so it considers it a mixed type. `json_decode` without the associative array flag set to `true` would result in an object. But PHPStan does not know whether the object is iterative. So, it flags it as an error.

In the next release, we'll also introduce the ability to ignore specific errors. Stay tuned for that!

I'm closing this issue for now, since it doesn't seem to be a bug. It's just that PHPStan doesn't have complete info about what type `$item` is and what the json structure is for `$item->json`.

I am closing this issue. If you have any further questions, feel free to bump this thread. I will reply here. In case there's another issue, feel free to open a new one. Thanks!
