### ISSUE TITLE
Some checks don't work in a multitenancy app

### ISSUE THREAD

**Issue by RobertCordes** [enlightn/enlightn#40]
### Versions

* PHP version: 7.4.12
* Laravel version: 8.25.0
* Enlightn version: 1.9.0 OSS

### Description
Hi, I'm trying to run Enlightn in a multitenancy setup. I'm using the [laravel-multitenancy package from Spatie](https://spatie.be/docs/laravel-multitenancy/v1/introduction). Some checks just don't seem to work with this kind of setup.

### Steps to Reproduce
Nothing special. Just set up a Laravel app with the multitenancy package as per documentation.

**Expected behavior:**
For all the checks to work I guess 😇 Although I don't really expect this to work out of the box. For example [Invoker has a feature](https://beyondco.de/docs/invoker/connections#connection-configuration) where you can define some _preload code_. So the expected behavior would probably be some way to configure this.

**Actual behavior:**
When I run Enlightn some checks just throw an exception with `Target class [currentTenant] does not exist`. In the OSS version of Enlightn the following checks don't work:

-  Session Driver Analyzer
- CSRF Analyzer
- Encrypted Cookies Analyzer
- HTTP Only Cookie Analyzer

**Comment by paras-malhotra** [comment]
Hi @RobertCordes, after reading through the docs of the Multitenancy package, I reckon you may be calling app('currentTenant') in some of the config files or middleware. So, you may need to [set the current tenant](https://spatie.be/docs/laravel-multitenancy/v1/basic-usage/working-with-the-current-tenant#manually-setting-the-current-tenant) before Enlightn runs its checks, so that the config is set accordingly.

Can you check if adding the following code to your AppServiceProvider works?

```php
use Enlightn\Enlightn\Inspection\Inspector;

$this->app->afterResolving(Inspector::class, function ($inspector) {
        // Add preload code to set current tenant here
});
```

If this does work, then I can make a PR to provide a more elegant way of doing this using a callback like:
```
Enlightn::beforeRunning(function () {
        // Preload code here
});
```

**Comment by RobertCordes** [comment]
Hey @paras-malhotra, thanks for the quick reply. This works perfectly! Can't wait for the PR 😅
