### ISSUE TITLE
[Bug Report] Cannot call method startOfDay() on Carbon\Carbon|false.

### ISSUE THREAD

**Issue by drewbindon** [enlightn/enlightn#80]
### Versions

* PHP version: 7.4.24
* Laravel version: 6.20.31
* Enlightn version: 1.22.1
* Enlightn Pro version (if applicable): 1.16.0

### Description
When trying to run `startOf('day')` or `startOfDay()` method on Carbon\Carbon, Enlightn throws an `Enlightn\Enlightn\Analyzers\Reliability\InvalidMethodCallAnalyzer` error.

### Steps to Reproduce

**Expected behavior:**
Both these methods exist and Enlightn shouldn't be throwing an error.

```
use Carbon\Carbon;
...
$date = Carbon::createFromFormat('Y-m-d', '2021-10-25', 'America/Denver')
    ->startOfDay()
    ->setTimezone('UTC');
```
and
```
use Carbon\Carbon;
...
$date = Carbon::createFromFormat('Y-m-d', '2021-10-25', 'America/Denver')
    ->startOf('day')
    ->setTimezone('UTC');
```

**Actual behavior:**
Enlightn throws an error for both method calls.

<img width="1233" alt="Screen Shot 2021-10-25 at 10 17 32 AM" src="https://user-images.githubusercontent.com/35608232/138734178-f2468082-d28f-4ea8-96d1-ef9d53471beb.png">

### Additional Information

Have only tried in `--ci` mode, but suspect it happens on both since they're using the same analyzer.

**Comment by paras-malhotra** [comment]
This behaviour is expected because Carbon extends the PHP DateTime class and `createFromFormat` [can return `false`](https://www.php.net/manual/en/datetime.createfromformat.php).

Here's a [reference](https://stackoverflow.com/questions/69929433/why-do-i-get-error-when-try-to-convert-carbon-to-datetime) to help understand why PHPStan complains about this.
